Fix ldap.managed errors
Regression from 8db1d1e (#48666):
- AttributeError: 'tuple' object has no attribute 'encode'
- ValueError: too many values to unpack

Fixes: #52022.